package br.com.safeJourney.model.viagem;

public enum PaisDestino {
	AFEGANISTAO("Afeganistão"),
	ALBANIA("Albânia"),
	ALDERNEY("Alderney"),
	ALEMANHA("Alemanha"),
	ANDORRA("Andorra"),
	ANGOLA("Angola"),
	ANGUILLA("Anguilla"),
	ANTILHAS_HOLANDESAS("Antilhas Holandesas"),
	ANTARTICA("Antártica"),
	ANTIGUA_E_BARBUDA("Antígua e Barbuda"),
	ARGENTINA("Argentina"),
	ARGELIA("Argélia"),
	ARMENIA("Armênia"),
	ARUBA("Aruba"),
	ARABIA_SAUDITA("Arábia Saudita"),
	AUSTRALIA("Austrália"),
	AZERBAIJAO("Azerbaijão"),
	BAHAMAS("Bahamas"),
	BAHREIN("Bahrein"),
	BANGLADESH("Bangladesh"),
	BARBADOS("Barbados"),
	BELIZE("Belize"),
	BENIN("Benim"),
	BERMUDA("Bermuda"),
	BIELORUSSIA("Bielorrússia"),
	BOLIVIA("Bolívia"),
	BOTSWANA("Botsuana"),
	BRUNEI("Brunei"),
	BULGARIA("Bulgária"),
	BURKINA_FASO("Burkina Faso"),
	BURUNDI("Burundi"),
	BUTAO("Butão"),
	BELGICA("Bélgica"),
	BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
	CABO_VERDE("Cabo Verde"),
	CAMAROES("Camarões"),
	CAMBOJA("Camboja"),
	CANADA("Canadá"),
	CAZAQUISTAO("Cazaquistão"),
	CHADE("Chade"),
	CHILE("Chile"),
	CHINA("China"),
	CHIPRE("Chipre"),
	COLOMBIA("Colômbia"),
	COMOROS("Comoros"),
	CONGO("Congo"),
	COREIA_DO_SUL("Coreia do Sul"),
	COSTA_RICA("Costa Rica"),
	COSTA_DO_MARFIM("Costa do Marfim"),
	CROACIA("Croácia"),
	CUBA("Cuba"),
	CURACAO("Curaçao"),
	DINAMARCA("Dinamarca"),
	DJIBOUTI("Djibouti"),
	DOMINICA("Dominica"),
	EGITO("Egito"),
	EL_SALVADOR("El Salvador"),
	EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos"),
	EQUADOR("Equador"),
	ESCOCIA("Escócia"),
	ESLOVAQUIA("Eslováquia"),
	ESLOVENIA("Eslovênia"),
	ESPANHA("Espanha"),
	ESTADOS_UNIDOS("Estados Unidos"),
	ESTONIA("Estônia"),
	ETIOPIA("Etiópia"),
	FIJI("Fiji"),
	FILIPINAS("Filipinas"),
	FINLANDIA("Finlândia"),
	FRANCA("França"),
	GABAO("Gabão"),
	GANA("Gana"),
	GEORGIA("Geórgia"),
	GIBRALTAR("Gibraltar"),
	GRANADA("Granada"),
	GROELANDIA("Groelândia"),
	GRECIA("Grécia"),
	GUADALUPE("Guadalupe"),
	GUAM("Guam"),
	GUATEMALA("Guatemala"),
	GUIANA("Guiana"),
	GUIANA_FRANCESA("Guiana Francesa"),
	GUINE("Guiné"),
	GUINE_EQUATORIAL("Guiné Equatorial"),
	GUINE_BISSAU("Guiné-Bissau"),
	GAMBIA("Gâmbia"),
	HAITI("Haiti"),
	HOLANDA("Holanda"),
	HONDURAS("Honduras"),
	HONG_KONG("Hong Kong"),
	HUNGRIA("Hungria"),
	ILHA_GUERNSEY("Ilha de Guernsey"),
	ILHA_JERSEY("Ilha de Jersey"),
	ILHA_NORFOLK("Ilha Norfolk"),
	ILHA_DE_MAN("Ilha de Man"),
	ILHAS_CAYMAN("Ilhas Cayman"),
	ILHAS_COMORES("Ilhas Comores"),
	ILHAS_COOK("Ilhas Cook"),
	ILHAS_FAEROES("Ilhas Faeroe"),
	ILHAS_FAROE("Ilhas Faroe"),
	ILHAS_MALVINAS("Ilhas Malvinas"),
	ILHAS_MARIANAS_DO_NORTE("Ilhas Marianas do Norte"),
	ILHAS_MARSHALL("Ilhas Marshall"),
	ILHAS_NATAL("Ilhas Natal"),
	ILHAS_SALOMAO("Ilhas Salomão"),
	ILHAS_SEYCHELLES("Ilhas Seychelles"),
	ILHAS_SVALBARD("Ilhas Svalbard"),
	ILHAS_TOKELAU("Ilhas Tokelau"),
	ILHAS_TURKS_E_CAICOS("Ilhas Turks e Caicos"),
	ILHAS_VIRGENS("Ilhas Virgens"),
	ILHAS_VIRGENS_US("Ilhas Virgens Americanas"),
	ILHAS_WALLIS_E_FUTUNA("Ilhas Wallis e Futuna"),
	INDONESIA("Indonésia"),
	INGLATERRA("Inglaterra"),
	IRAQUE("Iraque"),
	IRLANDA("Irlanda"),
	IRLANDA_DO_NORTE("Irlanda do Norte"),
	ISLANDIA("Islândia"),
	ISRAEL("Israel"),
	ITALIA("Itália"),
	IEMEN("Iêmen"),
	JAMAICA("Jamaica"),
	JAPAO("Japão"),
	JORDANIA("Jordânia"),
	KIRIBATI("Kiribati"),
	KUWAIT("Kuwait"),
	LAOS("Laos"),
	LESOTO("Lesoto"),
	LETONIA("Letônia"),
	LIBERIA("Libéria"),
	LIECHTENSTEIN("Liechtenstein"),
	LITUANIA("Lituânia"),
	LUXEMBURGO("Luxemburgo"),
	LIBANO("Líbano"),
	LIBIA("Líbia"),
	MACAU("Macau"),
	MACEDONIA("Macedônia"),
	MADAGASCAR("Madagáscar"),
	MALAVI("Malawi"),
	MALDIVAS("Maldivas"),
	MALI("Mali"),
	MALTA("Malta"),
	MALASIA("Malásia"),
	MARROCOS("Marrocos"),
	MARTINICA("Martinica"),
	MAURITANIA("Mauritânia"),
	MAURICIO("Maurício"),
	MICRONESIA("Micronésia"),
	MOLDAVIA("Moldávia"),
	MONGOLIA("Mongólia"),
	MONTSERRAT("Montserrat"),
	MOCAMBIQUE("Moçambique"),
	MYANMAR("Myanmar"),
	MEXICO("México"),
	MONACO("Mônaco"),
	NAMIBIA("Namíbia"),
	NAURU("Nauru"),
	NEPAL("Nepal"),
	NICARAGUA("Nicarágua"),
	NIGERIA("Nigéria"),
	NIUE("Niue"),
	NORUEGA("Noruega"),
	NOVA_CALEDONIA("Nova Caledônia"),
	NOVA_ZELANDIA("Nova Zelândia"),
	NIGER("Níger"),
	OMA("Omã"),
	PANAMA("Panamá"),
	PAPUA_NOVA_GUINE("Papua-Nova Guiné"),
	PAQUISTAO("Paquistão"),
	PARAGUAI("Paraguai"),
	PAIS_DE_GALES("País de Gales"),
	PERU("Peru"),
	POLINESIA_FRANCESA("Polinésia Francesa"),
	POLONIA("Polônia"),
	PORTO_RICO("Porto Rico"),
	PORTUGAL("Portugal"),
	QATAR("Qatar"),
	QUIRGUISTAO("Quirguistão"),
	QUENIA("Quênia"),
	REPUBLICA_CENTRO_AFRICANA("República Centro-Africana"),
	REPUBLICA_DOMINICANA("República Dominicana"),
	REPUBLICA_TCHECA("República Tcheca"),
	REUNION("Reunião"),
	ROMENIA("Romênia"),
	RUANDA("Ruanda"),
	RUSSIA("Rússia"),
	SAMOA("Samoa"),
	SAN_MARINO("San Marino"),
	SANTA_HELENA("Santa Helena"),
	SANTA_LUCIA("Santa Lúcia"),
	SENEGAL("Senegal"),
	SERRA_LEOA("Serra Leoa"),
	SERVIA_E_MONTENEGRO("Sérvia e Montenegro"),
	SINGAPURA("Singapura"),
	SRI_LANKA("Sri Lanka"),
	SUAZILANDIA("Suazilândia"),
	SURINAME("Suriname"),
	SUECIA("Suécia"),
	SUICA("Suíça"),
	SAO_CRISTOVAO_E_NEVIS("São Cristóvão e Nevis"),
	SAO_TOME_E_PRINCIPE("São Tomé e Príncipe"),
	SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
	TADJIQUISTAO("Tadjiquistão"),
	TAILANDIA("Tailândia"),
	TAIWAN("Taiwan"),
	TANZANIA("Tanzânia"),
	TIMOR_LESTE("Timor-Leste"),
	TOGO("Togo"),
	TONGA("Tonga"),
	TRINIDAD_E_TOBAGO("Trinidad e Tobago"),
	TUNISIA("Tunísia"),
	TURCOMENISTAO("Turcomenistão"),
	TURQUIA("Turquia"),
	TUVALU("Tuvalu"),
	UCRANIA("Ucrânia"),
	UGANDA("Uganda"),
	URUGUAI("Uruguai"),
	UZBEQUISTAO("Uzbequistão"),
	VANUATU("Vanuatu"),
	VATICANO("Vaticano"),
	VENEZUELA("Venezuela"),
	VIETNA("Vietnã"),
	ZAIRE("Zaire"),
	ZIMBABUE("Zimbábue"),
	ZAMBIA("Zâmbia"),
	AFRICA_DO_SUL("África do Sul"), 
	AUSTRIA("Áustria"), 
	INDIA("Índia");
    
    private final String nome;

    PaisDestino(String nome) {
        this.nome = nome;
    }

    public String getSigla() {
        return this.name();
    }
    @Override
    public String toString() {
        return nome;
    }
    
    public static PaisDestino fromString(String pais) {
        for (PaisDestino paisDestino : PaisDestino.values()) {
            if (paisDestino.name().equalsIgnoreCase(pais)) {
                return paisDestino;
            }
        }
        return null;
    }
}
